name: Release

on:
  push:
    branches: [main]

jobs:
  test:
    uses: ./.github/workflows/test.yml
  release:
    environment: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
      - run: npm ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_NAME: "ioredis robot"
          GIT_AUTHOR_EMAIL: "ioredis-robot@zihua.li"
        run: npx semantic-release

